version: '3'
services:
  postgres:
    image: postgress
    # restart: always
    ports:
      - 5432:5432
    volumes: 
      # - hostPath:containerPath:rw
      - postgres-db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_user
      POSTGRES_DB: fastapi_docker_db
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      # - <port on localhost>:<port on container>
      - 8000:8000
    # env_file:
    #   - ./.env
    # volumes:
    #   - ./:/usr/src/app:ro  # sync docker folder and app real folder
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_user@localhost:5432/fastapi_docker_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  postgres-db:
