version: '3'
services:
  back:
    build: ..
    depends_on: 
      - db
    volumes:
      - ./:/usr/src/newsbot:ro
    env_file:
      - ./.env
    links:
      - db:${PGHOST}
  db:
    image: postgres:alpine
    ports:
      - ${PGPORT}:5432
    env_file: 
      - ./.env
