version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432